version: "3.8"
services:
    db:
            container_name: sql-server-db
            image: "mcr.microsoft.com/mssql/server"
            ports:
            - "1401:1433"
            environment:
                SA_PASSWORD: "myDockerPassword321"
                ACCEPT_EULA: "Y"
